services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actual_server
    volumes:
      - ${DOCKER_DIR}/budgeting/actualbudget/data:/data
      - ${DOCKER_DIR}/budgeting/actualbudget/config/config.json:/app/config.json
    healthcheck:
      # Enable health check for the instance
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    networks:
      - proxy
    labels:
    #TRAEFIK
      - "traefik.enable=true"
      - "traefik.http.routers.actual-server.entrypoints=http"
      - "traefik.http.routers.actual-server.rule=Host(`budget.${DOMAIN}`)" #Domain
      - "traefik.http.middlewares.actual-server-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.actual-server.middlewares=actual-server-https-redirect"
      - "traefik.http.routers.actual-server-secure.entrypoints=https"
      - "traefik.http.routers.actual-server-secure.rule=Host(`budget.${DOMAIN}`)" #Domain
      - "traefik.http.routers.actual-server-secure.tls=true"
      - "traefik.http.routers.actual-server-secure.service=actual-server"
      - "traefik.http.services.actual-server.loadbalancer.server.port=5006" #port
      - "traefik.docker.network=proxy"
    #HOMEPAGE
      - homepage.group=${HOMEPAGE_GROUP}
      - homepage.name=actual-budget
      - homepage.icon=actual-budget.png
      - homepage.href=https://budget.${DOMAIN}
    security_opt:
      - no-new-privileges:true