services:
  actual-ai:
    image: docker.io/sakowicz/actual-ai:latest
    container_name: actual-ai
    restart: unless-stopped
    depends_on:
      - actual_server
    # env_file:
    #   - .env.actual-ai
    environment:

    networks:
      - proxy
    security_opt:
      - no-new-privileges:true