services:
  simplefin-notifier:
    image: ghcr.io/thiagogpa/simplefin-notifier:latest
    container_name: simplefin-notifier
    depends_on:
      - actual_server
    # env_file:
    #   - .env.simplefin-notifier
    environment:
      - GOTIFY_APP_TOKEN=${GOTIFY_APP_TOKEN}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - SIMPLEFIN_BRIDGE_TOKEN=${SIMPLEFIN_BRIDGE_TOKEN}
      - GOTIFY_BASE_URL=https://gotify.${DOMAIN}
      - CREDENTIALS_PATH=/app/credentials
      - FILE_LOGGING_LEVEL=INFO
      - CRON_SCHEDULE=0 12 * * *
    volumes:
      -  ${DOCKER_DIR}/budgeting/simplefin-notifier/credentials:/app/credentials
    restart: unless-stopped
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true