services:
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:stable
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      # - ESPHOME_DASHBOARD_USE_PING=true #optional
      - ESPHOME_DATA_DIR=/data #Environment variable for separated data from configs, you shouldn't need to change this
    volumes:
       - ${DOCKER_DIR}/home_automation/esphome/config:/config 
       - esphome-data:/data
       - /dev/shm/esphome-cache:/cache
    ports:
      # - 6052:6052 #Web UI
      - 6123:6123/udp # WebSocket logging
      - 8266:8266/tcp # OTA updates
      # - 5353:5353 #/udp #mdns
    networks:
      - hassionet
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.esphome.entrypoints=http"
      - "traefik.http.routers.esphome.rule=Host(`esphome.${DOMAIN}`)" 
      - "traefik.http.middlewares.esphome-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.esphome.middlewares=esphome-https-redirect"
      - "traefik.http.routers.esphome-secure.entrypoints=https"
      - "traefik.http.routers.esphome-secure.rule=Host(`esphome.${DOMAIN}`)" 
      - "traefik.http.routers.esphome-secure.tls=true"
      - "traefik.http.routers.esphome-secure.service=esphome"
      - "traefik.http.services.esphome.loadbalancer.server.port=6052" 
      - "traefik.http.routers.esphome-secure.middlewares=middlewares-authentik@file" 
      - "traefik.docker.network=proxy"
    #homepage
      - homepage.group=${HOMEPAGE_GROUP}
      - homepage.name=esphome
      - homepage.icon=/icons/esphome-dark.png
      - homepage.href=https://esphome.${DOMAIN}
    security_opt:
      - no-new-privileges:true

volumes:
  esphome-data: